name: Standard Registrations TEST Environment
on: [push]
jobs:
  Regression:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: e2e-testing
    steps:
      - uses: actions/checkout@v2
        with:
         ref: assets

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          env: true
          node-version: "12.x"
      - run: npm install

      - run: npm run assetsStandardRegistrations
        if: ${{ always() }}
        env:
          CYPRESS_PPR_DOMAIN: ${{ secrets.PPR_DOMAIN }}
          CYPRESS_BCSC_USERNAME: ${{secrets.BCSC_USERNAME}}
          CYPRESS_BCSC_PASSWORD: ${{secrets.BCSC_PASSWORD}}
          CYPRESS_TYPE: ${{secrets.TYPE}}          